spring.application.name=seo-tool
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/seo_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=mySuperSecretKeyForJWTTokenGenerationSeoAnalyzerApp2024
jwt.expiration=86400000

aws.region=ap-south-1
aws.accessKeyId=YOUR_ACCESS_KEY
aws.secretKey=YOUR_SECRET_KEY
aws.s3.bucket=seo-analyzer-reports